/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT dm6446.cdb */

/*  Include Header File  */
#include "dm6446cfg.h"

/*  Config Structures */
/*  Handles  */
